// Lead Master Azim
export const FETCH_ALL_LEADS_START =  'FETCH_ALL_LEADS_START'
export const FETCH_ALL_LEADS_SUCCESS =  'FETCH_ALL_LEADS_SUCCESS'
export const FETCH_ALL_LEADS_FAIL =  'FETCH_ALL_LEADS_FAIL'

export const FETCH_DESIGNATION_START =  'FETCH_DESIGNATION_START'
export const FETCH_DESIGNATION_SUCCESS =  'FETCH_DESIGNATION_SUCCESS'
export const FETCH_DESIGNATION_FAIL =  'FETCH_DESIGNATION_FAIL'

export const FETCH_TODAY_LEADS_START =  'FETCH_TODAY_LEADS_START'
export const FETCH_TODAY_LEADS_SUCCESS =  'FETCH_TODAY_LEADS_SUCCESS'
export const FETCH_TODAY_LEADS_FAIL =  'FETCH_TODAY_LEADS_FAIL'

export const FETCH_OPEN_LEADS_START =  'FETCH_OPEN_LEADS_START'
export const FETCH_OPEN_LEADS_SUCCESS =  'FETCH_OPEN_LEADS_SUCCESS'
export const FETCH_OPEN_LEADS_FAIL =  'FETCH_OPEN_LEADS_FAIL'

export const FETCH_CONVERTED_LEADS_START =  'FETCH_CONVERTED_LEADS_START'
export const FETCH_CONVERTED_LEADS_SUCCESS =  'FETCH_CONVERTED_LEADS_SUCCESS'
export const FETCH_CONVERTED_LEADS_FAIL =  'FETCH_CONVERTED_LEADS_FAIL'

export const FETCH_FAILED_LEADS_START =  'FETCH_FAILED_LEADS_START'
export const FETCH_FAILED_LEADS_SUCCESS =  'FETCH_FAILED_LEADS_SUCCESS'
export const FETCH_FAILED_LEADS_FAIL =  'FETCH_FAILED_LEADS_FAIL'

export const FETCH_LEAD_CATEGORY_START = 'FETCH_LEAD_CATEGORY_START'
export const FETCH_LEAD_CATEGORY_SUCCESS = 'FETCH_LEAD_CATEGORY_SUCCESS'
export const FETCH_LEAD_CATEGORY_FAIL = 'FETCH_LEAD_CATEGORY_FAIL'

export const FETCH_HISTORY_START = 'FETCH_HISTORY_START'
export const FETCH_HISTORY_SUCCESS = 'FETCH_HISTORY_SUCCESS'
export const FETCH_HISTORY_FAIL = 'FETCH_HISTORY_FAIL'

export const CREATE_LEAD_START = 'CREATE_LEAD_START'
export const CREATE_LEAD_SUCCESS = 'CREATE_LEAD_SUCCESS'
export const CREATE_LEAD_FAIL = 'CREATE_LEAD_FAIL'


export const STORE_FORM_SUCCESS = 'STORE_FORM_SUCCESS'




// Addresses
export const FETCH_STATES_START = 'FETCH_STATES_START'
export const FETCH_STATES_SUCCESS = 'FETCH_STATES_SUCCESS'
export const FETCH_STATES_FAIL = 'FETCH_STATES_FAIL'

export const FETCH_CITIES_START = 'FETCH_CITIES_START'
export const FETCH_CITIES_SUCCESS = 'FETCH_CITIES_SUCCESS'
export const FETCH_CITIES_FAIL = 'FETCH_CITIES_FAIL'



// Login Shiva 
export const LOGIN_START =  'LOGIN_START'
export const LOGIN_SUCCESS =  'LOGIN_SUCCESS'
export const LOGIN_FAIL =  'LOGIN_FAIL'


export const AUTH_LOGOUT_START = 'AUTH_LOGOUT_START';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';
export const AUTH_LOGOUT_FAIL = 'AUTH_LOGOUT_FAIL';

export const FETCH_USER_DETAILS_START = 'FETCH_USER_DETAILS_START'
export const FETCH_USER_DETAILS_SUCCESS = 'FETCH_USER_DETAILS_SUCCESS'
export const FETCH_USER_DETAILS_FAIL = 'FETCH_USER_DETAILS_FAIL'

export const FETCH_HIERARCHY_START = 'FETCH_HIERARCHY_START'
export const FETCH_HIERARCHY_SUCCESS = 'FETCH_HIERARCHY_SUCCESS'
export const FETCH_HIERARCHY_FAIL = 'FETCH_HIERARCHY_FAIL'

export const FORGOT_PASSWORD_START =  'FORGOT_PASSWORD_START'
export const FORGOT_PASSWORD_SUCCESS =  'FORGOT_PASSWORD_SUCCESS'
export const FORGOT_PASSWORD_FAIL =  'FORGOT_PASSWORD_FAIL'

export const HOME_START =  'HOME_START'
export const HOME_SUCCESS =  'HOME_SUCCESS'
export const HOME_FAIL =  'HOME_FAIL'

export const ACTIVITIES_START =  'ACTIVITIES_START'
export const ACTIVITIES_SUCCESS =  'ACTIVITIES_SUCCESS'
export const ACTIVITIES_FAIL =  'ACTIVITIES_FAIL'


